# src/infrastructure/loaders/pdf_loader.py
import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import fitz
from src.core.config import Settings
from src.core.book import Book
from src.core.section import Section
from src.core.table_of_content import TableOfContent
from src.core.helpers import new_id

from .file_type import FileType
from .loader import Loader


@dataclass
class _RawEntry:
    title: str
    raw_text: str
    index: int
    level: int


@dataclass
class _PathCounter:
    def __init__(self) -> None:
        self._counters: Dict[int, int] = {}

    def next(self, level: int) -> str:
        self._counters[level] = self._counters.get(level, 0) + 1
        levels_to_reset = [l for l in self._counters if l > level]
        for l in levels_to_reset:
            del self._counters[l]
        parts = [f"{self._counters.get(i, 0):03d}" for i in range(1, level + 1)]
        return ".".join(parts)


class PdfLoader(Loader):
    def __init__(self, settings: Settings):
        self._settings = settings

    def load(self, path: Path) -> Book:
        with fitz.open(str(path)) as doc:
            title = self._detect_title(doc, path)
            raw_entries = self._extract_entries(doc)

        book_id = self._generate_toc_hash(title, raw_entries)
        book = Book(
            id=book_id,
            title=title,
            source_format=FileType.Pdf,
            file_path=str(path),
            source_filename=path.name,
            total_chapters=0,  # will be updated later
            toc=[],  # will be populated
        )

        # Build TOC tree and sections in one pass
        counter = _PathCounter()
        toc_entries: List[TableOfContent] = []
        stack: List[TableOfContent] = []  # stack for parent hierarchy

        for idx, entry in enumerate(raw_entries):
            if entry.level > self._settings.deepest_level:
                continue

            path_id = counter.next(entry.level)

            # Create Section object
            section = Section(
                book_id=book_id,
                path_id=path_id,
                parent_path_id=".".join(path_id.split(".")[:-1]),
                title=entry.title,
                level=entry.level,
                raw_text=entry.raw_text,
                extraction_status="NONE",
            )
            # Section.id will be auto-generated by Entity base class

            # Determine parent TOC entry
            while stack and stack[-1].level >= entry.level:
                stack.pop()
            parent_id = stack[-1].id if stack else None

            # Create TOC entry, linking to the Section
            toc_entry = TableOfContent(
                book_id=book_id,
                section_id=section.id,  # link to Section (section.id is set automatically after flush)
                parent_id=parent_id,
                level=entry.level,
                order=idx,
                title=entry.title,
                section=section,  # directly set the relationship (this will be saved automatically)
            )
            toc_entries.append(toc_entry)
            book.toc.append(
                toc_entry
            )  # attach to Book – cascade will save both TOC and Section

            # Update parent stack
            stack.append(toc_entry)

        book.total_chapters = len([t for t in toc_entries if t.level == 1])
        return book

    def _generate_toc_hash(self, title: str, entries: List[_RawEntry]) -> str:
        fingerprint_parts = [title]
        for entry in entries:
            fingerprint_parts.append(f"{entry.level}:{entry.title}")
        fingerprint_str = "|".join(fingerprint_parts)
        return hashlib.sha256(fingerprint_str.encode()).hexdigest()

    def _extract_entries(self, doc: fitz.Document) -> List[_RawEntry]:
        toc = doc.get_toc()
        if toc:
            return self._extract_via_toc(doc, toc)
        return self._extract_via_heuristic(doc)

    def _extract_via_toc(self, doc: fitz.Document, toc: list) -> List[_RawEntry]:
        entries: list[_RawEntry] = []
        for i in range(len(toc)):
            level, title, start_page = toc[i]
            end_page = toc[i + 1][2] if i + 1 < len(toc) else doc.page_count
            start_index = max(0, start_page - 1)
            end_index = max(0, end_page - 1)
            text = self._extract_page_range(doc, start_index, end_index)
            if not text:
                continue
            entries.append(_RawEntry(title=title, raw_text=text, index=i, level=level))
        return entries

    def _extract_via_heuristic(self, doc: fitz.Document) -> List[_RawEntry]:
        entries: list[_RawEntry] = []
        pending_title = "Introduction"
        pending_level = 1
        pending_text: list[str] = []
        index = 0

        def _flush() -> None:
            nonlocal index
            body = " ".join(pending_text).strip()
            if body:
                entries.append(
                    _RawEntry(
                        title=pending_title,
                        raw_text=body,
                        level=pending_level,
                        index=index,
                    )
                )
                index += 1

        for page in doc:
            for block in page.get_text("dict").get("blocks", []):
                if block.get("type") != 0:
                    continue
                for line in block.get("lines", []):
                    for span in line.get("spans", []):
                        text = span["text"].strip()
                        if not text:
                            continue
                        level = self._heading_level(span["size"])
                        if level and 2 < len(text) < 100:
                            _flush()
                            pending_title = text
                            pending_level = level
                            pending_text = []
                        else:
                            pending_text.append(text)
            pending_text.append("\n")
        _flush()
        return entries

    def _build_toc_and_sections(
        self, entries: List[_RawEntry], book_id: str
    ) -> (List[Section], List[TableOfContent]):
        """
        Builds lists of Section and TableOfContent objects from extracted entries.
        Returns (sections, toc_entries).
        """
        sections: List[Section] = []
        toc_entries: List[TableOfContent] = []
        counter = _PathCounter()
        stack: List[TableOfContent] = []  # stack of parent TOC entries per level

        for idx, entry in enumerate(entries):
            if entry.level > self._settings.deepest_level:
                continue

            # Generate deterministic path ID for ordering
            path_id = counter.next(entry.level)

            # Create Section object
            section = Section(
                path_id=path_id,
                parent_path_id=".".join(path_id.split(".")[:-1]),
                title=entry.title,
                level=entry.level,
                raw_text=entry.raw_text,
                extraction_status="NONE",  # default
            )
            # The Section id will be auto-generated by Entity base class (new_id).
            sections.append(section)

            # Find parent TOC entry
            parent_id = None
            while stack and stack[-1].level >= entry.level:
                stack.pop()
            if stack:
                parent_id = stack[-1].id

            # Create TOC entry
            toc_entry = TableOfContent(
                id=new_id(),  # explicit ID (or let it auto‑generate via default_factory)
                book_id=book_id,
                section_id=section.id,
                parent_id=parent_id,
                level=entry.level,
                order=idx,
                title=entry.title,
            )
            toc_entries.append(toc_entry)

            # Update stack: add this entry as potential parent for deeper levels
            stack.append(toc_entry)

        return sections, toc_entries

    def _extract_page_range(self, doc: fitz.Document, first: int, last: int) -> str:
        parts = []
        for page_num in range(first, min(last, doc.page_count)):
            parts.append(doc[page_num].get_text("text"))
        return "\n\n".join(parts).strip()

    @staticmethod
    def _heading_level(font_size: float) -> Optional[int]:
        if font_size >= 20:
            return 1
        if font_size >= 16:
            return 2
        if font_size >= 13:
            return 3
        return None

    @staticmethod
    def _detect_title(doc: fitz.Document, file_path: Path) -> str:
        metadata_title = doc.metadata.get("title", "").strip()
        garbage_phrases = ["microsoft word", "untitled", "document", "scan", "copy"]
        is_garbage = any(phrase in metadata_title.lower() for phrase in garbage_phrases)
        if metadata_title and not is_garbage:
            return metadata_title
        clean_filename = file_path.stem.replace("_", " ").replace("-", " ").title()
        return clean_filename
