# src/infrastructure/loaders/pdf_loader.py
"""PDF document loader.

Mirrors ``EpubLoader`` exactly in structure and public API:

* ``get_stable_id(path)`` – stable SHA-256 from title + TOC shape.
* ``extract_raw(path)``   – returns ``ExtractedBookData`` with sections attached.

Responsibilities are separated across three collaborators, one per concern:

``PdfLoader`` itself owns only:
  - file opening / caching
  - title detection
  - stable-ID computation
  - attaching ``Section`` objects to ``TocNode`` instances

Everything else lives in the builder or the extractor.
"""

import hashlib
import logging
from pathlib import Path
from typing import Dict, Optional

import fitz

from src.domain.config import Settings
from src.domain.section import Section
from src.domain.toc_node import TocNode
from src.ingestion._loaders._base import ExtractedBookData, Loader
from src.ingestion._loaders.toc_builders.pdf_toc_builder import PdfTocBuilder
from src.ingestion._loaders.text_extractors.pdf_text_extractor import (
    PdfTextExtractor,
)

logger = logging.getLogger(__name__)

# Metadata title values that are not meaningful (generated by Word, scanners …)
_GARBAGE_TITLE_PHRASES = {"microsoft word", "untitled", "document", "scan", "copy"}


class PdfLoader(Loader):
    """Parses a PDF file and returns an ``ExtractedBookData`` DTO.

    Parsing is lazy and cached per path, so calling ``get_stable_id``
    followed by ``extract_raw`` on the same path only opens the file once.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._current_path: Optional[Path] = None
        self._cached_data: Optional[dict] = None

    # ------------------------------------------------------------------
    # Public API  (same contract as EpubLoader)
    # ------------------------------------------------------------------

    def get_stable_id(self, path: Path) -> str:
        """Compute a stable SHA-256 ID from the book's title and TOC shape."""
        data = self._ensure_loaded(path)
        return self._compute_stable_id(data["title"], data["toc_root"])

    def extract_raw(self, path: Path) -> ExtractedBookData:
        """Parse the PDF and return a fully-populated ``ExtractedBookData``."""
        data = self._ensure_loaded(path)
        logger.info("PdfLoader: extracting content for %s", path)

        content_map: Dict[str, str] = PdfTextExtractor.extract_texts(
            data["doc"], data["toc_root"]
        )
        self._attach_sections(data["toc_root"], content_map)

        return ExtractedBookData(
            title=data["title"],
            author=data["author"],
            toc_root=data["toc_root"],
        )

    # ------------------------------------------------------------------
    # Internal loading + caching  (mirrors EpubLoader._ensure_loaded)
    # ------------------------------------------------------------------

    def _ensure_loaded(self, path: Path) -> dict:
        """Open and parse the PDF, or return the cached result."""
        if self._current_path == path and self._cached_data:
            return self._cached_data

        doc = fitz.open(str(path))
        title = self._detect_title(doc, path)
        toc_root = PdfTocBuilder.build(doc)

        self._current_path = path
        self._cached_data = {
            "doc": doc,
            "title": title,
            "author": doc.metadata.get("author") or None,
            "toc_root": toc_root,
        }
        return self._cached_data

    # ------------------------------------------------------------------
    # Stable book ID  (mirrors EpubLoader._compute_stable_id)
    # ------------------------------------------------------------------

    @staticmethod
    def _compute_stable_id(title: str, toc_root: TocNode) -> str:
        """SHA-256 over title and the depth-annotated title of every node."""
        parts = [title]

        def collect(node: TocNode, depth: int) -> None:
            for child in node.children:
                # Include page (href) so two books with the same TOC titles
                # but different pagination produce different IDs.
                parts.append(f"{depth}:{child.title}:{child.href}")
                collect(child, depth + 1)

        collect(toc_root, 1)
        return hashlib.sha256("|".join(parts).encode()).hexdigest()

    # ------------------------------------------------------------------
    # Attach sections  (mirrors EpubLoader._attach_sections)
    # ------------------------------------------------------------------

    def _attach_sections(self, node: TocNode, content_map: Dict[str, str]) -> None:
        """Recursively attach ``Section`` objects to each ``TocNode``.

        ``href`` is the page-number string used as the key in
        ``content_map``.  Nodes without text are skipped (no section
        attached), matching EPUB loader behaviour.
        """
        if node.level > 0 and node.href:
            raw_text = content_map.get(node.href, "")
            section = Section(
                raw_text=raw_text if raw_text else "",
                extraction_status="NONE",
            )
            node.section = section
            node.section_id = section.id

        for child in node.children:
            self._attach_sections(child, content_map)

    # ------------------------------------------------------------------
    # Metadata helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _detect_title(doc: fitz.Document, file_path: Path) -> str:
        """Return a clean title, falling back to the filename stem."""
        metadata_title = (doc.metadata.get("title") or "").strip()
        is_garbage = any(
            phrase in metadata_title.lower() for phrase in _GARBAGE_TITLE_PHRASES
        )
        if metadata_title and not is_garbage:
            return metadata_title
        return file_path.stem.replace("_", " ").replace("-", " ").title()
