JOB_PARSE_BOOK = "parse_book"
JOB_EXTRACT_FACTS = "extract_facts"
JOB_AUDIT_SUMMARY = "audit_summary"

QUEUE_PARSE = "parse_queue"
QUEUE_FACT = "fact_queue"
QUEUE_AUDIT = "audit_queue"

RESOURCE_BOOK = "book"
RESOURCE_SECTION = "section"
RESOURCE_SUMMARY = "summary"

JOB_QUEUE_MAP = {
    JOB_PARSE_BOOK: QUEUE_PARSE,
    JOB_EXTRACT_FACTS: QUEUE_FACT,
    JOB_AUDIT_SUMMARY: QUEUE_AUDIT,
}

JOB_RESOURCE_MAP = {
    JOB_PARSE_BOOK: RESOURCE_BOOK,
    JOB_EXTRACT_FACTS: RESOURCE_SECTION,
    JOB_AUDIT_SUMMARY: RESOURCE_SUMMARY,
}
