import os

import pytest
from sqlmodel import SQLModel, select
from src.core.atomic_fact import AtomicFact
from src.core.enums import Tier
from src.core.models import Book, Chapter, Section
from src.infrastructure.adapters.mariadb.database_context import DatabaseContext
from src.infrastructure.loaders.file_type import FileType
from src.infrastructure.persistence.atomic_facts_repo import AtomicFactRepository


@pytest.mark.asyncio
class TestAtomicFactRepository:

    @pytest.fixture
    async def db_context(self):
        """Setup MariaDB test database with all tables."""
        connection_url = os.getenv(
            "TEST_MARIADB_URL",
            "mysql+aiomysql://root:password@localhost:3306/insight_auditor_test",
        )
        ctx = DatabaseContext(connection_url)

        async with ctx.engine.begin() as conn:
            # SQLModel handles the creation order to respect Foreign Keys
            await conn.run_sync(SQLModel.metadata.create_all)

        yield ctx

        async with ctx.engine.begin() as conn:
            await conn.run_sync(SQLModel.metadata.drop_all)
        await ctx.engine.dispose()

    @pytest.fixture
    async def sample_section(self, db_context):
        """Creates the full chain: Book -> Chapter -> Section based on your specific fields."""
        async with db_context.get_session() as session:
            # 1. Create Book (Satisfying all required fields)
            book = Book(
                title="Python Deep Dive",
                author="Fluent Pythonist",
                source_format=FileType.Pdf,  # Assuming PDF exists in your FileType enum
                file_path="/path/to/book.pdf",
                source_filename="book.pdf",
                total_chapters=1,
            )
            session.add(book)
            await session.flush()

            # 2. Create Chapter
            chapter = Chapter(
                title="Chapter 1: Objects", path_id="001", index=1, book_id=book.id
            )
            session.add(chapter)
            await session.flush()

            # 3. Create Section (Satisfying level and chapter relationship)
            section = Section(
                title="Mutable Objects",
                path_id="001.001",
                level=1,
                chapter_id=chapter.id,
                raw_text="Python lists are mutable sequences that can be changed in place.",
            )
            session.add(section)

            await session.commit()
            await session.refresh(section)
            return section

    async def test_save_fact_in_hierarchy(self, db_context, sample_section):
        """Verify that a fact can be saved when the full hierarchy exists."""
        section = sample_section

        async with db_context.get_session() as session:
            repo = AtomicFactRepository(session)

            # Create the fact using the section.id (auto-generated by Entity)
            fact = AtomicFact(
                section_id=section.id,
                path_id=section.path_id,
                point="Lists allow in-place modification.",
                rank=Tier.CRITICAL,
                reason="Core behavioral characteristic of mutability",
            )

            await repo.save(fact)
            await session.commit()

            # Verification
            saved = await repo.find_by_id(fact.id)
            assert saved is not None
            assert saved.section_id == section.id
            assert saved.point == fact.point

    async def test_find_by_section_filter(self, db_context, sample_section):
        """Verify repository can filter facts using the auto-generated section ID."""
        section = sample_section

        async with db_context.get_session() as session:
            repo = AtomicFactRepository(session)

            fact_1 = AtomicFact(
                section_id=section.id, path_id="1", point="Fact A", rank=Tier.IMPORTANT
            )
            fact_2 = AtomicFact(
                section_id=section.id, path_id="2", point="Fact B", rank=Tier.NUANCE
            )

            session.add_all([fact_1, fact_2])
            await session.commit()

            # Test the repository filter method
            results = await repo.find_by_section(section.id)

            assert len(results) == 2
            assert all(f.section_id == section.id for f in results)

    async def test_deletion_integrity(self, db_context, sample_section):
        section_id = sample_section.id

        async with db_context.get_session() as session:
            # Fetch fresh from DB at the start
            section = await session.get(Section, section_id)

            repo = AtomicFactRepository(session)
            fact = AtomicFact(
                section_id=section.id,
                path_id="99",
                point="Temp",
                rank=Tier.NUANCE,
                reason="Test",
            )
            await repo.save(fact)
            await session.commit()

            # Delete
            await repo.delete(fact.id)
            await session.commit()

            # Verification: Fetch AGAIN to see the state after deletion
            result = await session.execute(
                select(Section).where(Section.id == section_id)
            )
            db_section = result.scalar_one()

            # If word_count is still 0, the fixture didn't save it correctly.
            # You can force a recount here for the test:
            if db_section.word_count == 0 and db_section.raw_text:
                # This proves the text is there but the column was saved wrong
                assert len(db_section.raw_text.split()) > 0

            assert db_section.word_count > 0
